### ISSUE TITLE
내역화면 색상 데이터바인딩 과정에서 오류 발생하는 경우

### ISSUE THREAD

**Issue by hanchang97** [woowa-techcamp-2022/android-accountbook-10#32]
```
Process: com.nimok97.accountbook, PID: 20643
    java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
        at android.graphics.Color.parseColor(Color.java:1383)
        at com.nimok97.accountbook.databinding.ItemHistoryContentBindingImpl.executeBindings(ItemHistoryContentBindingImpl.java:162)
        at androidx.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:512)
        at androidx.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:484)

                                                   ...
```

**Comment by hanchang97** [comment]
색상 데이터에 기본 값을 설정해 우선 null 인 상태로 들어올 수 없게 조치
-> 버그 재발생 되는지 체크하기
